//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinedale.Turtle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vinedale.Turtle.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandBackExampleText {
            get {
                return ResourceManager.GetString("CommandBackExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells the turtle to move backwards X steps..
        /// </summary>
        internal static string CommandBackHelpText {
            get {
                return ResourceManager.GetString("CommandBackHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell me how far to go backwards as a number..
        /// </summary>
        internal static string CommandBackWrongTypeError {
            get {
                return ResourceManager.GetString("CommandBackWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the screen without moving the turtle..
        /// </summary>
        internal static string CommandCleanHelpText {
            get {
                return ResourceManager.GetString("CommandCleanHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the screen and returns the turtle to its start point..
        /// </summary>
        internal static string CommandClearGraphicsHelpText {
            get {
                return ResourceManager.GetString("CommandClearGraphicsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandForwardExampleText {
            get {
                return ResourceManager.GetString("CommandForwardExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells the turtle to move forward X steps..
        /// </summary>
        internal static string CommandForwardHelpText {
            get {
                return ResourceManager.GetString("CommandForwardHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell me how far to go forwards as a number..
        /// </summary>
        internal static string CommandForwardWrongTypeError {
            get {
                return ResourceManager.GetString("CommandForwardWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the turtle back in its starting place..
        /// </summary>
        internal static string CommandHomeHelpText {
            get {
                return ResourceManager.GetString("CommandHomeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandLeftExampleText {
            get {
                return ResourceManager.GetString("CommandLeftExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells the turtle to turn left X degrees..
        /// </summary>
        internal static string CommandLeftHelpText {
            get {
                return ResourceManager.GetString("CommandLeftHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell me how far to turn as a number..
        /// </summary>
        internal static string CommandLeftWrongTypeError {
            get {
                return ResourceManager.GetString("CommandLeftWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowers the pen, so the turtle starts drawing..
        /// </summary>
        internal static string CommandPenDownHelpText {
            get {
                return ResourceManager.GetString("CommandPenDownHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifts the pen, so the turtle stops drawing..
        /// </summary>
        internal static string CommandPenUpHelpText {
            get {
                return ResourceManager.GetString("CommandPenUpHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandRightExampleText {
            get {
                return ResourceManager.GetString("CommandRightExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells the turtle to turn right X degrees..
        /// </summary>
        internal static string CommandRightHelpText {
            get {
                return ResourceManager.GetString("CommandRightHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell me how far to turn as a number..
        /// </summary>
        internal static string CommandRightWrongTypeError {
            get {
                return ResourceManager.GetString("CommandRightWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandSetXExampleText {
            get {
                return ResourceManager.GetString("CommandSetXExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tells the turtle to change its X-coordinate..
        /// </summary>
        internal static string CommandSetXHelpText {
            get {
                return ResourceManager.GetString("CommandSetXHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell me where to move to as a number..
        /// </summary>
        internal static string CommandSetXWrongTypeError {
            get {
                return ResourceManager.GetString("CommandSetXWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw the turtle on the screen..
        /// </summary>
        internal static string CommandShowTurtleHelpText {
            get {
                return ResourceManager.GetString("CommandShowTurtleHelpText", resourceCulture);
            }
        }
    }
}
