using Logo.Interpretation;

namespace Logo.Tokens
{
    /// <summary>
    /// Encapsulates the results of operator evaluation.
    /// </summary>
    public class OperatorEvaluationResult
    {
        /// <summary>
        /// The success or failure of operator evaluation.
        /// </summary>
        public InterpretationResult Result { get; set; }

        /// <summary>
        /// The value of the result.
        /// </summary>
        public LogoValue Value { get; set; }

        /// <summary>
        /// Any error message generated by operator evaluation.
        /// </summary>
        public string Message { get; set; }
    }
}
