using Logo.Core.Interpretation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Logo.Core.Tokens
{
    /// <summary>
    /// Encapsulates the results of operator evaluation.
    /// </summary>
    public class OperatorEvaluationResult
    {
        /// <summary>
        /// The success or failure of operator evaluation.
        /// </summary>
        public InterpretationResult Result { get; set; }

        /// <summary>
        /// Any error message generated by operator evaluation.
        /// </summary>
        public string Message { get; set; }
    }
}
