//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandAbsExampleText {
            get {
                return ResourceManager.GetString("CommandAbsExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the absolute (positive) value of a number..
        /// </summary>
        internal static string CommandAbsHelpText {
            get {
                return ResourceManager.GetString("CommandAbsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use abs on numbers..
        /// </summary>
        internal static string CommandAbsWrongTypeError {
            get {
                return ResourceManager.GetString("CommandAbsWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandAndExampleText {
            get {
                return ResourceManager.GetString("CommandAndExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns &apos;true&apos; if everything in the list is true..
        /// </summary>
        internal static string CommandAndHelpText {
            get {
                return ResourceManager.GetString("CommandAndHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use and on lists..
        /// </summary>
        internal static string CommandAndWrongTypeError {
            get {
                return ResourceManager.GetString("CommandAndWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandArctanExampleText {
            get {
                return ResourceManager.GetString("CommandArctanExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the arctangent value of a number..
        /// </summary>
        internal static string CommandArctanHelpText {
            get {
                return ResourceManager.GetString("CommandArctanHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use arctan on numbers..
        /// </summary>
        internal static string CommandArctanWrongTypeError {
            get {
                return ResourceManager.GetString("CommandArctanWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to word.
        /// </summary>
        internal static string CommandAsciiExampleText {
            get {
                return ResourceManager.GetString("CommandAsciiExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the ASCII number of the first letter of the word..
        /// </summary>
        internal static string CommandAsciiHelpText {
            get {
                return ResourceManager.GetString("CommandAsciiHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use ascii on a string..
        /// </summary>
        internal static string CommandAsciiWrongTypeError {
            get {
                return ResourceManager.GetString("CommandAsciiWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandButfirstExampleText {
            get {
                return ResourceManager.GetString("CommandButfirstExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the list, without its first item..
        /// </summary>
        internal static string CommandButfirstHelpText {
            get {
                return ResourceManager.GetString("CommandButfirstHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use butfirst on something that isn&apos;t a list..
        /// </summary>
        internal static string CommandButfirstWrongTypeError {
            get {
                return ResourceManager.GetString("CommandButfirstWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandButlastExampleText {
            get {
                return ResourceManager.GetString("CommandButlastExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the list, without its last item..
        /// </summary>
        internal static string CommandButlastHelpText {
            get {
                return ResourceManager.GetString("CommandButlastHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use butlast on something that isn&apos;t a list..
        /// </summary>
        internal static string CommandButlastWrongTypeError {
            get {
                return ResourceManager.GetString("CommandButlastWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandCharExampleText {
            get {
                return ResourceManager.GetString("CommandCharExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts the number to a letter..
        /// </summary>
        internal static string CommandCharHelpText {
            get {
                return ResourceManager.GetString("CommandCharHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use char on a number..
        /// </summary>
        internal static string CommandCharWrongTypeError {
            get {
                return ResourceManager.GetString("CommandCharWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A.
        /// </summary>
        internal static string CommandClearnameExampleText {
            get {
                return ResourceManager.GetString("CommandClearnameExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes me forget variable A..
        /// </summary>
        internal static string CommandClearnameHelpText {
            get {
                return ResourceManager.GetString("CommandClearnameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes me forget all variables..
        /// </summary>
        internal static string CommandClearnamesHelpText {
            get {
                return ResourceManager.GetString("CommandClearnamesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandCosExampleText {
            get {
                return ResourceManager.GetString("CommandCosExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the cosine of a number..
        /// </summary>
        internal static string CommandCosHelpText {
            get {
                return ResourceManager.GetString("CommandCosHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use cos on numbers..
        /// </summary>
        internal static string CommandCosWrongTypeError {
            get {
                return ResourceManager.GetString("CommandCosWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list] or word.
        /// </summary>
        internal static string CommandCountExampleText {
            get {
                return ResourceManager.GetString("CommandCountExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of things in a list or the number of letters in a word..
        /// </summary>
        internal static string CommandCountHelpText {
            get {
                return ResourceManager.GetString("CommandCountHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandDifferenceExampleText {
            get {
                return ResourceManager.GetString("CommandDifferenceExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes Y from X..
        /// </summary>
        internal static string CommandDifferenceHelpText {
            get {
                return ResourceManager.GetString("CommandDifferenceHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to take that kind of thing from that..
        /// </summary>
        internal static string CommandDifferenceTypeError {
            get {
                return ResourceManager.GetString("CommandDifferenceTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandExpExampleText {
            get {
                return ResourceManager.GetString("CommandExpExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns e to the power of a number..
        /// </summary>
        internal static string CommandExpHelpText {
            get {
                return ResourceManager.GetString("CommandExpHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use exp on numbers..
        /// </summary>
        internal static string CommandExpWrongTypeError {
            get {
                return ResourceManager.GetString("CommandExpWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use first on an empty list..
        /// </summary>
        internal static string CommandFirstEmptyListError {
            get {
                return ResourceManager.GetString("CommandFirstEmptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandFirstExampleText {
            get {
                return ResourceManager.GetString("CommandFirstExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the first thing in a list..
        /// </summary>
        internal static string CommandFirstHelpText {
            get {
                return ResourceManager.GetString("CommandFirstHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use first on lists..
        /// </summary>
        internal static string CommandFirstWrongTypeError {
            get {
                return ResourceManager.GetString("CommandFirstWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [list].
        /// </summary>
        internal static string CommandFputExampleText {
            get {
                return ResourceManager.GetString("CommandFputExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add something to the start of a list..
        /// </summary>
        internal static string CommandFputHelpText {
            get {
                return ResourceManager.GetString("CommandFputHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only fput something into a list..
        /// </summary>
        internal static string CommandFputWrongTypeError {
            get {
                return ResourceManager.GetString("CommandFputWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandGreaterpExampleText {
            get {
                return ResourceManager.GetString("CommandGreaterpExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decides whether or not X is greater than Y..
        /// </summary>
        internal static string CommandGreaterpHelpText {
            get {
                return ResourceManager.GetString("CommandGreaterpHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use greaterp on numbers..
        /// </summary>
        internal static string CommandGreaterpWrongTypeError {
            get {
                return ResourceManager.GetString("CommandGreaterpWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does {1} things..
        /// </summary>
        internal static string CommandHelpActionCountOutput {
            get {
                return ResourceManager.GetString("CommandHelpActionCountOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;something.
        /// </summary>
        internal static string CommandHelpExampleText {
            get {
                return ResourceManager.GetString("CommandHelpExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what I currently know how to do:.
        /// </summary>
        internal static string CommandHelpHeadingOutput {
            get {
                return ResourceManager.GetString("CommandHelpHeadingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out information on what something does..
        /// </summary>
        internal static string CommandHelpHelpText {
            get {
                return ResourceManager.GetString("CommandHelpHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t give you help with {0} because I don&apos;t know how to do it..
        /// </summary>
        internal static string CommandHelpUnknownProcedureError {
            get {
                return ResourceManager.GetString("CommandHelpUnknownProcedureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandIntExampleText {
            get {
                return ResourceManager.GetString("CommandIntExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces the number X to the nearest smaller whole number..
        /// </summary>
        internal static string CommandIntHelpText {
            get {
                return ResourceManager.GetString("CommandIntHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use int on a number..
        /// </summary>
        internal static string CommandIntWrongTypeError {
            get {
                return ResourceManager.GetString("CommandIntWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [list].
        /// </summary>
        internal static string CommandItemExampleText {
            get {
                return ResourceManager.GetString("CommandItemExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the Xth item in a list..
        /// </summary>
        internal static string CommandItemHelpText {
            get {
                return ResourceManager.GetString("CommandItemHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t enough things in this list for me to give you that item..
        /// </summary>
        internal static string CommandItemIndexOutOfBoundsError {
            get {
                return ResourceManager.GetString("CommandItemIndexOutOfBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I number the items in a list starting with 1 and going up..
        /// </summary>
        internal static string CommandItemNegativeIndexError {
            get {
                return ResourceManager.GetString("CommandItemNegativeIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only get an item from a list using its number..
        /// </summary>
        internal static string CommandItemWrongTypeErrorFirstArgument {
            get {
                return ResourceManager.GetString("CommandItemWrongTypeErrorFirstArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use item on lists..
        /// </summary>
        internal static string CommandItemWrongTypeErrorSecondArgument {
            get {
                return ResourceManager.GetString("CommandItemWrongTypeErrorSecondArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use last on an empty list..
        /// </summary>
        internal static string CommandLastEmptyListError {
            get {
                return ResourceManager.GetString("CommandLastEmptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandLastExampleText {
            get {
                return ResourceManager.GetString("CommandLastExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the last thing in a list..
        /// </summary>
        internal static string CommandLastHelpText {
            get {
                return ResourceManager.GetString("CommandLastHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use last on lists..
        /// </summary>
        internal static string CommandLastWrongTypeError {
            get {
                return ResourceManager.GetString("CommandLastWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandLnExampleText {
            get {
                return ResourceManager.GetString("CommandLnExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the natural logarithm of a number..
        /// </summary>
        internal static string CommandLnHelpText {
            get {
                return ResourceManager.GetString("CommandLnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use ln on numbers..
        /// </summary>
        internal static string CommandLnWrongTypeError {
            get {
                return ResourceManager.GetString("CommandLnWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandLogExampleText {
            get {
                return ResourceManager.GetString("CommandLogExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the base-10 logarithm of a number..
        /// </summary>
        internal static string CommandLogHelpText {
            get {
                return ResourceManager.GetString("CommandLogHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use log on numbers..
        /// </summary>
        internal static string CommandLogWrongTypeError {
            get {
                return ResourceManager.GetString("CommandLogWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [list].
        /// </summary>
        internal static string CommandLputExampleText {
            get {
                return ResourceManager.GetString("CommandLputExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add something to the end of a list..
        /// </summary>
        internal static string CommandLputHelpText {
            get {
                return ResourceManager.GetString("CommandLputHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only lput something into a list..
        /// </summary>
        internal static string CommandLputWrongTypeError {
            get {
                return ResourceManager.GetString("CommandLputWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...{0} to {1}.
        /// </summary>
        internal static string CommandMakeEndDebugMessage {
            get {
                return ResourceManager.GetString("CommandMakeEndDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A B.
        /// </summary>
        internal static string CommandMakeExampleText {
            get {
                return ResourceManager.GetString("CommandMakeExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets variable A to value B..
        /// </summary>
        internal static string CommandMakeHelpText {
            get {
                return ResourceManager.GetString("CommandMakeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting variable....
        /// </summary>
        internal static string CommandMakeStartDebugMessage {
            get {
                return ResourceManager.GetString("CommandMakeStartDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandMinusExampleText {
            get {
                return ResourceManager.GetString("CommandMinusExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the negative of a number..
        /// </summary>
        internal static string CommandMinusHelpText {
            get {
                return ResourceManager.GetString("CommandMinusHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use minus on numbers..
        /// </summary>
        internal static string CommandMinusWrongTypeError {
            get {
                return ResourceManager.GetString("CommandMinusWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out how many things I can do..
        /// </summary>
        internal static string CommandNodesHelpText {
            get {
                return ResourceManager.GetString("CommandNodesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} procedures and {1} procedure names..
        /// </summary>
        internal static string CommandNodesOutput {
            get {
                return ResourceManager.GetString("CommandNodesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandOrExampleText {
            get {
                return ResourceManager.GetString("CommandOrExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns &apos;true&apos; if anything in the list is true..
        /// </summary>
        internal static string CommandOrHelpText {
            get {
                return ResourceManager.GetString("CommandOrHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use or on lists..
        /// </summary>
        internal static string CommandOrWrongTypeError {
            get {
                return ResourceManager.GetString("CommandOrWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t pick something from an empty list..
        /// </summary>
        internal static string CommandPickEmptyListError {
            get {
                return ResourceManager.GetString("CommandPickEmptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandPickExampleText {
            get {
                return ResourceManager.GetString("CommandPickExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picks a random thing from a list..
        /// </summary>
        internal static string CommandPickHelpText {
            get {
                return ResourceManager.GetString("CommandPickHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only pick something from a list..
        /// </summary>
        internal static string CommandPickWrongTypeError {
            get {
                return ResourceManager.GetString("CommandPickWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number Pi (3.14159...)..
        /// </summary>
        internal static string CommandPiHelpText {
            get {
                return ResourceManager.GetString("CommandPiHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandPowerExampleText {
            get {
                return ResourceManager.GetString("CommandPowerExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns X to the power Y..
        /// </summary>
        internal static string CommandPowerHelpText {
            get {
                return ResourceManager.GetString("CommandPowerHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use power on numbers..
        /// </summary>
        internal static string CommandPowerWrongTypeError {
            get {
                return ResourceManager.GetString("CommandPowerWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [list].
        /// </summary>
        internal static string CommandPrintExampleText {
            get {
                return ResourceManager.GetString("CommandPrintExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the contents of a list..
        /// </summary>
        internal static string CommandPrintHelpText {
            get {
                return ResourceManager.GetString("CommandPrintHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandProductExampleText {
            get {
                return ResourceManager.GetString("CommandProductExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns X times Y..
        /// </summary>
        internal static string CommandProductHelpText {
            get {
                return ResourceManager.GetString("CommandProductHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use product on numbers..
        /// </summary>
        internal static string CommandProductWrongTypeError {
            get {
                return ResourceManager.GetString("CommandProductWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t divide by zero..
        /// </summary>
        internal static string CommandQuotientDivideByZeroError {
            get {
                return ResourceManager.GetString("CommandQuotientDivideByZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandQuotientExampleText {
            get {
                return ResourceManager.GetString("CommandQuotientExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns X divided by Y..
        /// </summary>
        internal static string CommandQuotientHelpText {
            get {
                return ResourceManager.GetString("CommandQuotientHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use quotient on numbers..
        /// </summary>
        internal static string CommandQuotientWrongTypeError {
            get {
                return ResourceManager.GetString("CommandQuotientWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycles spare space that I was using..
        /// </summary>
        internal static string CommandRecycleHelpText {
            get {
                return ResourceManager.GetString("CommandRecycleHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t divide by zero..
        /// </summary>
        internal static string CommandRemainderDivideByZeroError {
            get {
                return ResourceManager.GetString("CommandRemainderDivideByZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandRemainderExampleText {
            get {
                return ResourceManager.GetString("CommandRemainderExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the remainder after X is divided by Y..
        /// </summary>
        internal static string CommandRemainderHelpText {
            get {
                return ResourceManager.GetString("CommandRemainderHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use remainder on numbers..
        /// </summary>
        internal static string CommandRemainderWrongTypeError {
            get {
                return ResourceManager.GetString("CommandRemainderWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [list].
        /// </summary>
        internal static string CommandRepeatExampleText {
            get {
                return ResourceManager.GetString("CommandRepeatExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs a list of things, X number of times..
        /// </summary>
        internal static string CommandRepeatHelpText {
            get {
                return ResourceManager.GetString("CommandRepeatHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only repeat a list of things..
        /// </summary>
        internal static string CommandRepeatWrongListTypeError {
            get {
                return ResourceManager.GetString("CommandRepeatWrongListTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to know how many times to repeat something..
        /// </summary>
        internal static string CommandRepeatWrongRepeatTypeError {
            get {
                return ResourceManager.GetString("CommandRepeatWrongRepeatTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandRoundExampleText {
            get {
                return ResourceManager.GetString("CommandRoundExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds a number to the nearest whole number..
        /// </summary>
        internal static string CommandRoundHelpText {
            get {
                return ResourceManager.GetString("CommandRoundHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use round on numbers..
        /// </summary>
        internal static string CommandRoundWrongTypeError {
            get {
                return ResourceManager.GetString("CommandRoundWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandSinExampleText {
            get {
                return ResourceManager.GetString("CommandSinExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the sine of a number..
        /// </summary>
        internal static string CommandSinHelpText {
            get {
                return ResourceManager.GetString("CommandSinHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use sin on numbers..
        /// </summary>
        internal static string CommandSinWrongTypeError {
            get {
                return ResourceManager.GetString("CommandSinWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the amount of space I am using..
        /// </summary>
        internal static string CommandSpaceHelpText {
            get {
                return ResourceManager.GetString("CommandSpaceHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CommandSqrtExampleText {
            get {
                return ResourceManager.GetString("CommandSqrtExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the square root of a number..
        /// </summary>
        internal static string CommandSqrtHelpText {
            get {
                return ResourceManager.GetString("CommandSqrtHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use sqrt on numbers that are bigger than zero..
        /// </summary>
        internal static string CommandSqrtLessThanZeroError {
            get {
                return ResourceManager.GetString("CommandSqrtLessThanZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use sqrt on numbers..
        /// </summary>
        internal static string CommandSqrtWrongTypeError {
            get {
                return ResourceManager.GetString("CommandSqrtWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y.
        /// </summary>
        internal static string CommandSumExampleText {
            get {
                return ResourceManager.GetString("CommandSumExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds two numbers together..
        /// </summary>
        internal static string CommandSumHelpText {
            get {
                return ResourceManager.GetString("CommandSumHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use sum on numbers..
        /// </summary>
        internal static string CommandSumWrongTypeError {
            get {
                return ResourceManager.GetString("CommandSumWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string CommandTanExampleText {
            get {
                return ResourceManager.GetString("CommandTanExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the tangent of a number..
        /// </summary>
        internal static string CommandTanHelpText {
            get {
                return ResourceManager.GetString("CommandTanHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only use tan on numbers..
        /// </summary>
        internal static string CommandTanWrongTypeError {
            get {
                return ResourceManager.GetString("CommandTanWrongTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t understand your expression &apos;{0}&apos; because something inside it wasn&apos;t finished..
        /// </summary>
        internal static string ExpressionConstructorIncompleteError {
            get {
                return ResourceManager.GetString("ExpressionConstructorIncompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t tell me how to do {0}..
        /// </summary>
        internal static string InterpretorDefineProcedureProcedureIsNonRedefinableError {
            get {
                return ResourceManager.GetString("InterpretorDefineProcedureProcedureIsNonRedefinableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Token: type {1}, literal value &apos;{2}&apos;..
        /// </summary>
        internal static string InterpretorDumpTokenOutput {
            get {
                return ResourceManager.GetString("InterpretorDumpTokenOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expression &apos;{0}&apos; contained something that was incomplete, so I couldn&apos;t work out what it meant..
        /// </summary>
        internal static string InterpretorEvaluateExpressionContentsIncompleteContentsError {
            get {
                return ResourceManager.GetString("InterpretorEvaluateExpressionContentsIncompleteContentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating expression {0}..
        /// </summary>
        internal static string InterpretorEvaluateExpressionDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorEvaluateExpressionDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t see anything after your &apos;{0}&apos; sign in &apos;{1}&apos;..
        /// </summary>
        internal static string InterpretorEvaluateExpressionEndsWithOperatorError {
            get {
                return ResourceManager.GetString("InterpretorEvaluateExpressionEndsWithOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t work out how to understand &apos;{0}&apos;..
        /// </summary>
        internal static string InterpretorEvaluateExpressionGeneralError {
            get {
                return ResourceManager.GetString("InterpretorEvaluateExpressionGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t see anything before your &apos;{0}&apos; sign in &apos;{1}&apos;..
        /// </summary>
        internal static string InterpretorEvaluateExpressionStartsWithOperatorError {
            get {
                return ResourceManager.GetString("InterpretorEvaluateExpressionStartsWithOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating list {0}..
        /// </summary>
        internal static string InterpretorEvaluateListContentsDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorEvaluateListContentsDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your list &apos;{0}&apos; contained something that was incomplete, so I couldn&apos;t work out what it meant..
        /// </summary>
        internal static string InterpretorEvaluateListIncompleteContentsError {
            get {
                return ResourceManager.GetString("InterpretorEvaluateListIncompleteContentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what to do with the expression {0}..
        /// </summary>
        internal static string InterpretorExecuteTokenBufferCannotExecuteBareExpressionError {
            get {
                return ResourceManager.GetString("InterpretorExecuteTokenBufferCannotExecuteBareExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what to do with the list {0}..
        /// </summary>
        internal static string InterpretorExecuteTokenBufferCannotExecuteBareListError {
            get {
                return ResourceManager.GetString("InterpretorExecuteTokenBufferCannotExecuteBareListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to {0}..
        /// </summary>
        internal static string InterpretorExecuteWordUndefinedProcedureError {
            get {
                return ResourceManager.GetString("InterpretorExecuteWordUndefinedProcedureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t tell me how to do that..
        /// </summary>
        internal static string InterpretorInterpretProcedureIsNonRedefinableError {
            get {
                return ResourceManager.GetString("InterpretorInterpretProcedureIsNonRedefinableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tokens returned by tokeniser..
        /// </summary>
        internal static string InterpretorInterpretTokenCountDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorInterpretTokenCountDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokeniser result was: {0}..
        /// </summary>
        internal static string InterpretorInterpretTokeniserResultDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorInterpretTokeniserResultDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded module {0}.
        /// </summary>
        internal static string InterpretorLoadedModuleDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorLoadedModuleDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading module {0} from assembly {1}.
        /// </summary>
        internal static string InterpretorModuleLoadingDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorModuleLoadingDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered procedure {0}.
        /// </summary>
        internal static string InterpretorRegisteredProcedureDebugMessage {
            get {
                return ResourceManager.GetString("InterpretorRegisteredProcedureDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.  This is Vinedale..
        /// </summary>
        internal static string InterpretorWelcomeMessage {
            get {
                return ResourceManager.GetString("InterpretorWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t understand your list &apos;{0}&apos; because something inside it wasn&apos;t finished..
        /// </summary>
        internal static string ListConstructorIncompleteError {
            get {
                return ResourceManager.GetString("ListConstructorIncompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to add those kinds of things together..
        /// </summary>
        internal static string OperatorAdditionTypeError {
            get {
                return ResourceManager.GetString("OperatorAdditionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to divide that kind of thing by that..
        /// </summary>
        internal static string OperatorDivisionTypeError {
            get {
                return ResourceManager.GetString("OperatorDivisionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to multiply those kinds of things together..
        /// </summary>
        internal static string OperatorMultiplicationTypeError {
            get {
                return ResourceManager.GetString("OperatorMultiplicationTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to take that kind of thing from that..
        /// </summary>
        internal static string OperatorSubtractionTypeError {
            get {
                return ResourceManager.GetString("OperatorSubtractionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to do that kind of operation..
        /// </summary>
        internal static string OperatorUnknownOperationError {
            get {
                return ResourceManager.GetString("OperatorUnknownOperationError", resourceCulture);
            }
        }
    }
}
