//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syntax {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syntax() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logo.Resources.Syntax", typeof(Syntax).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        internal static string AbsCmd {
            get {
                return ResourceManager.GetString("AbsCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string AndCmd {
            get {
                return ResourceManager.GetString("AndCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arctan.
        /// </summary>
        internal static string ArctanCmd {
            get {
                return ResourceManager.GetString("ArctanCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascii.
        /// </summary>
        internal static string AsciiCmd {
            get {
                return ResourceManager.GetString("AsciiCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butfirst.
        /// </summary>
        internal static string ButfirstCmd {
            get {
                return ResourceManager.GetString("ButfirstCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butlast.
        /// </summary>
        internal static string ButlastCmd {
            get {
                return ResourceManager.GetString("ButlastCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string CharCmd {
            get {
                return ResourceManager.GetString("CharCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearname.
        /// </summary>
        internal static string ClearnameCmd {
            get {
                return ResourceManager.GetString("ClearnameCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearnames.
        /// </summary>
        internal static string ClearnamesCmd {
            get {
                return ResourceManager.GetString("ClearnamesCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        internal static string CosCmd {
            get {
                return ResourceManager.GetString("CosCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string CountCmd {
            get {
                return ResourceManager.GetString("CountCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to difference.
        /// </summary>
        internal static string DifferenceCmd {
            get {
                return ResourceManager.GetString("DifferenceCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ ].
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp.
        /// </summary>
        internal static string ExpCmd {
            get {
                return ResourceManager.GetString("ExpCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string FirstCmd {
            get {
                return ResourceManager.GetString("FirstCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fput.
        /// </summary>
        internal static string FputCmd {
            get {
                return ResourceManager.GetString("FputCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpCmd {
            get {
                return ResourceManager.GetString("HelpCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string IntCmd {
            get {
                return ResourceManager.GetString("IntCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string ItemCmd {
            get {
                return ResourceManager.GetString("ItemCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string LastCmd {
            get {
                return ResourceManager.GetString("LastCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        internal static string LnCmd {
            get {
                return ResourceManager.GetString("LnCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string LogCmd {
            get {
                return ResourceManager.GetString("LogCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lput.
        /// </summary>
        internal static string LputCmd {
            get {
                return ResourceManager.GetString("LputCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make.
        /// </summary>
        internal static string MakeCmd {
            get {
                return ResourceManager.GetString("MakeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nodes.
        /// </summary>
        internal static string NodesCmd {
            get {
                return ResourceManager.GetString("NodesCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string OrCmd {
            get {
                return ResourceManager.GetString("OrCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pi.
        /// </summary>
        internal static string PiCmd {
            get {
                return ResourceManager.GetString("PiCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pr.
        /// </summary>
        internal static string PrCmd {
            get {
                return ResourceManager.GetString("PrCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print.
        /// </summary>
        internal static string PrintCmd {
            get {
                return ResourceManager.GetString("PrintCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recycle.
        /// </summary>
        internal static string RecycleCmd {
            get {
                return ResourceManager.GetString("RecycleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        internal static string RepeatCmd {
            get {
                return ResourceManager.GetString("RepeatCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string RoundCmd {
            get {
                return ResourceManager.GetString("RoundCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        internal static string SinCmd {
            get {
                return ResourceManager.GetString("SinCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space.
        /// </summary>
        internal static string SpaceCmd {
            get {
                return ResourceManager.GetString("SpaceCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        internal static string SqrtCmd {
            get {
                return ResourceManager.GetString("SqrtCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        internal static string TanCmd {
            get {
                return ResourceManager.GetString("TanCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
